name: Zappa Deploy

on:
  push:
    branches: 
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Create Virtual Environment
      run: |
        pip install virtualenv
        virtualenv --python=3.8 zappa-deploy-env
        source zappa-deploy-env/bin/activate
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: ap-northeast-2
        
    - name: Install Dependencies
      run: |
        source zappa-deploy-env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy dev
      working-directory: ./app
      env:
        VIRTUAL_ENV: ./zappa-deploy-env
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: us-west-2
      run: |
        zappa update dev
